config/routes.rb
Rails.application.routes.draw do
  
  resources :hours
  root 'home#index'

  get 'home/index'

  devise_for :users

end

app/models/hour.rb
class Hour < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @hello = "Hello #{current_user.email}"
  end
end

app/controllers/hours_controller.rb
class HoursController < ApplicationController
  before_action :set_hour, only: [:show, :edit, :update, :destroy]

  # GET /hours
  # GET /hours.json
  def index
    @hours = Hour.all.where("(deleted = false or deleted is null) and user_id = #{current_user.id}").order(:date)
  end

  # GET /hours/1
  # GET /hours/1.json
  def show
  end

  # GET /hours/new
  def new
    @hour = Hour.new
  end

  # GET /hours/1/edit
  def edit
  end

  # POST /hours
  # POST /hours.json
  def create
    @hour = Hour.new(hour_params)

    @hour.user_id = current_user.id
    @hour.date = DateTime.now

    respond_to do |format|
      if @hour.save
        format.html { redirect_to hours_url, notice: 'Hour was successfully created.' }
        format.json { render :show, status: :created, location: @hour }
      else
        format.html { render :new }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hours/1
  # PATCH/PUT /hours/1.json
  def update
    respond_to do |format|
      if @hour.update(hour_params)
        format.html { redirect_to hours_url, notice: 'Hour was successfully updated.' }
        format.json { render :show, status: :ok, location: @hour }
      else
        format.html { render :edit }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hours/1
  # DELETE /hours/1.json
  def destroy
    
    @hour.update_attributes(:deleted => true)

    respond_to do |format|
      format.html { redirect_to hours_url, notice: 'Hour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hour
      @hour = Hour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hour_params
      params.require(:hour).permit(:user_id, :date, :deleted, :description, :kind)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def date_to_hour(date)
        date.strftime("%H:%M")
    end

    def date_to_dateformat(date)
        date.strftime("%d/%m/%Y")
    end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hours_helper.rb
module HoursHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<p> <%= @hello %></p>

app/views/hours/_form.html.erb
<%= form_for(@hour) do |f| %>
  <% if @hour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hour.errors.count, "error") %> prohibited this hour from being saved:</h2>

      <ul>
      <% @hour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
        
  </div class="field">
    <%= f.label :date %><br>  
    <div id="time"></div>
  </div>
  <br/>
  
  <div class="field">
    <%= f.label :kind %><br>
    <%= f.select :kind, options_for_select(["Entrada 1","Saída 1","Entrada 2","Saída 2"]), :style => "width: 18%;" , :class => "custom-select custom-select-sm" %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, :style => "width: 18%;", :placeholder => "Description", :class => "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  function checkTime(i) {
      if (i < 10) {
        i = "0" + i;
      }
      return i;
    }
  
  function startTime() {
    var today = new Date();
    var h = today.getHours();
    var m = today.getMinutes();
    var s = today.getSeconds();
    // add a zero in front of numbers<10
    m = checkTime(m);
    s = checkTime(s);
    document.getElementById('time').innerHTML = h + ":" + m + ":" + s;
    t = setTimeout(function() {
      startTime()
    }, 500);
  }
  startTime();
</script>

app/views/hours/edit.html.erb
<h1>Editing Hour</h1>

<%= render 'form' %>

<%= link_to 'Show', @hour %> |
<%= link_to 'Back', hours_path %>

app/views/hours/index.html.erb
<h1>Listing Hours</h1>

<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Hour</th>
      <th>Description</th>
      <th>Kind</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @hours.each do |hour| %>
      <tr>
        <td><%= date_to_dateformat(hour.date) %></td>
        <td><%= date_to_hour(hour.date) %></td>
        <td><%= hour.description %></td>
        <td><%= hour.kind %></td>
        <td><%= link_to 'Edit', edit_hour_path(hour) %></td>
        <td><%= link_to 'Destroy', hour, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hour', new_hour_path %>

app/views/hours/new.html.erb
<h1>New Hour</h1>

<%= render 'form' %>

<%= link_to 'Back', hours_path %>

app/views/hours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @hour.user.email %>
</p>

<p>
  <strong>Date:</strong>
  <%= date_to_hour(@hour.date) %>
</p>

<p>
  <strong>Description:</strong>
  <%= @hour.description %>
</p>

<%= link_to 'Edit', edit_hour_path(@hour) %> |
<%= link_to 'Back', hours_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hours</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>
    <%= render partial: "layouts/shared/navigation" %>
  <% end %>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>

</body>
</html>

app/views/layouts/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#conteudoNavbarSuportado" aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Alterna navegação">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="conteudoNavbarSuportado">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/hours">Hours</a>
      </li>
      <li class="nav-item">
        <%= link_to("Logout", destroy_user_session_path, method: :delete, class: "nav-link") %>
      </li>
    </ul>
  </div>
</nav>